# Generated by Django 4.0.4 on 2022-06-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name': 'Pefil de usuario', 'verbose_name_plural': 'Perfiles de usuarios'},
        ),
        migrations.AddField(
            model_name='user_profile',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
