# Generated by Django 4.0.4 on 2022-06-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_profile_firts_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='link_url',
            field=models.URLField(blank=True),
        ),
    ]
