# Generated by Django 4.0.4 on 2022-06-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_biblio', models.CharField(max_length=100)),
                ('autor_biblio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inst_edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_inst', models.CharField(max_length=100)),
                ('ubicacion_inst', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obra_arq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obra', models.CharField(max_length=100)),
                ('autor_obra', models.CharField(max_length=100, unique=True)),
                ('ubicacion_obra', models.CharField(max_length=100, null=True)),
                ('año', models.IntegerField(null=True)),
                ('tipo', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
