# Generated by Django 4.0.4 on 2022-06-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliografia',
            options={'verbose_name': 'Bibliografia', 'verbose_name_plural': 'Bibliografias'},
        ),
        migrations.AlterModelOptions(
            name='inst_edu',
            options={'verbose_name': 'Institución educativa', 'verbose_name_plural': 'Instituciones educativas'},
        ),
        migrations.AlterModelOptions(
            name='obra_arq',
            options={'verbose_name': 'Obra de Arquitectura', 'verbose_name_plural': 'Obras de Arquitectura'},
        ),
    ]
