# Generated by Django 4.0.4 on 2022-06-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_bibliografia_options_alter_inst_edu_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bibliografia',
            new_name='Arquitecto',
        ),
        migrations.DeleteModel(
            name='Inst_edu',
        ),
        migrations.AlterModelOptions(
            name='arquitecto',
            options={'verbose_name': 'Arquitecto', 'verbose_name_plural': 'Arquitectos'},
        ),
        migrations.RenameField(
            model_name='arquitecto',
            old_name='autor_biblio',
            new_name='apellido_arqui',
        ),
        migrations.RenameField(
            model_name='arquitecto',
            old_name='nombre_biblio',
            new_name='nombre_arqui',
        ),
        migrations.RemoveField(
            model_name='obra_arq',
            name='autor_obra',
        ),
    ]
