# Generated by Django 4.0.4 on 2022-06-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_rename_bibliografia_arquitecto_delete_inst_edu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra_arq',
            name='arquitecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='app_blog.arquitecto'),
            preserve_default=False,
        ),
    ]
