# Generated by Django 4.0.4 on 2022-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_obra_arq_arquitecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra_arq',
            name='descripcion',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
