# Generated by Django 4.0.4 on 2022-06-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_rename_nombre_arqui_arquitecto_nombre_apellido_arqui_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquitecto',
            name='nombre_apellido_arqui',
        ),
        migrations.AddField(
            model_name='arquitecto',
            name='nombre_apellido_arquitecto',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
