# Generated by Django 4.0.4 on 2022-06-19 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_remove_arquitecto_nombre_apellido_arqui_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquitecto',
            old_name='nombre_apellido_arquitecto',
            new_name='nombre_apellido_arqui',
        ),
    ]
