# Generated by Django 4.0.4 on 2022-06-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_rename_nombre_apellido_arquitecto_arquitecto_nombre_apellido_arqui'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquitecto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='arquitectos'),
        ),
        migrations.AddField(
            model_name='obra_arq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='obras'),
        ),
    ]
