# Generated by Django 4.0.4 on 2022-06-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0011_alter_obra_arq_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra_arq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='obras'),
        ),
    ]
