# Generated by Django 4.0.4 on 2022-06-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0012_alter_obra_arq_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquitecto',
            name='image',
            field=models.ImageField(default='default.png', upload_to='arquitectos'),
        ),
        migrations.AlterField(
            model_name='obra_arq',
            name='image',
            field=models.ImageField(default='default.png', upload_to='obras'),
        ),
    ]
