# Generated by Django 4.0.4 on 2022-06-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0013_alter_arquitecto_image_alter_obra_arq_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquitecto',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='arquitectos'),
        ),
        migrations.AlterField(
            model_name='obra_arq',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='obras'),
        ),
    ]
