# Generated by Django 4.0.4 on 2022-06-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Titulos',
                'verbose_name_plural': 'Titulos',
            },
        ),
    ]
